image: node

pages:
  stage: deploy
  script:
    - npm install
    - resume export index.html --theme onepage
    - mkdir .public
    - cp -r ./site/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
